language: cpp
#dist: trusty

os: 
    - linux
#    - osx # TEMPORARILY disabled!!!
compiler:
    - gcc
    - clang 
env:
    - CMAKE_BUILD_TYPE=Debug
#    - CMAKE_BUILD_TYPE=Release #TODO!

before_install:
    # TEMPORARILY disabling tests that did not work at "day zero" (i.e. SF -> github migration)
    - if [ $TRAVIS_OS_NAME == osx ]; then export SEDCMD="sed -i ''"; fi 
    - if [ $TRAVIS_OS_NAME == linux ]; then export SEDCMD="sed -i"; fi 
    - $SEDCMD '/test_dicom.pro/d'            testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_fft_leak.pro/d'         testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_file_delete.pro/d'      testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_file_search.pro/d'      testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_finite.pro/d'           testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_fix.pro/d'              testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_formats.pro/d'          testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_image_statistics.pro/d' testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_make_dll.pro/d'         testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_n_tags.pro/d'           testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_obj_isa.pro/d'          testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_obj_new.pro/d'          testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_parse_url.pro/d'        testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_resolve_routine.pro/d'  testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_rounding.pro/d'         testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_step.pro/d'             testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_total.pro/d'            testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_typename.pro/d'         testsuite/Makefile.am # TODO!
    - $SEDCMD '/test_wait.pro/d'             testsuite/Makefile.am # TODO!

install:
    # https://github.com/travis-ci/travis-ci/issues/8613
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH; fi

    # https://github.com/Homebrew/brew/issues/1742#issuecomment-277308817
    - if [ $TRAVIS_OS_NAME == osx ]; then rm /usr/local/include/c++; fi 

    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends -y wget cmake libncurses-dev libreadline-gplv2-dev zlib1g-dev libgsl0-dev libplplot-dev libgraphicsmagick++1-dev libwxgtk2.8-dev libnetcdf-dev libhdf4-alt-dev libhdf5-serial-dev libfftw3-dev python-dev python-numpy-dev libudunits2-dev pslib-dev libgrib-api-dev; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gsl graphicsmagick udunits fftw eigen plplot wxwidgets netcdf hdf5; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export CMAKE_ARGS="${CMAKE_ARGS} -DHDF=OFF -DPSLIB=OFF -DEDITLINE=OFF -DREADLINE=OFF"; fi #TODO!

    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then wget http://bitbucket.org/eigen/eigen/get/3.3.2.zip; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then unzip 3.3.2.zip; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CMAKE_ARGS="${CMAKE_ARGS} -DEIGEN3DIR=../eigen-eigen-da9b4e14c255"; fi

script:
    - mkdir build
    - cd build
    - cmake $CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
    - make
    - make check || cat testsuite/Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
    - sudo make install
